In [2]:
import numpy as np

In [3]:
a = [1,2,3,5,7,12]

In [4]:
a

[1, 2, 3, 5, 7, 12]

In [5]:
a[2] = 10

In [7]:
b = a

In [8]:
b[2] = 3

In [9]:
b

[1, 2, 3, 5, 7, 12]

In [10]:
a

[1, 2, 3, 5, 7, 12]

In [13]:
import copy

In [14]:
b = copy.deepcopy(a)

In [15]:
b[2]=10

In [16]:
b

[1, 2, 10, 5, 7, 12]

In [17]:
a

[1, 2, 3, 5, 7, 12]

In [23]:
a = np.zeros((5,5))

In [28]:
matrix = np.random.rand(5, 5)*10

In [29]:
matrix

array([[1.33543001, 1.47744794, 8.51115844, 3.03554802, 4.9913561 ],
       [5.49466462, 1.84861977, 4.00965595, 7.32419518, 6.01589129],
       [9.68997008, 1.46199313, 7.78431397, 3.85433446, 2.62552185],
       [2.44721714, 5.0768986 , 4.89629036, 3.64041436, 4.09588439],
       [9.149371  , 4.25971482, 5.54054246, 9.58028595, 2.56667629]])

In [30]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [32]:
n = np.array(
    [[1,2,3],
    [4,5,6],
    [7,8,9]]
)

In [33]:
n[0,1]

np.int64(2)

In [35]:
n[:, 2] = [0, 1, 2]

In [ ]:
np.random.seed(2)
np.random.rand(5, 2)

array([[0.77132064, 0.02075195],
       [0.63364823, 0.74880388],
       [0.49850701, 0.22479665],
       [0.19806286, 0.76053071],
       [0.16911084, 0.08833981]])

In [39]:
np.random.randint(low=0, high=10, size=(5,5))

array([[4, 3, 0, 4, 6],
       [8, 1, 8, 4, 1],
       [3, 6, 5, 3, 9],
       [6, 9, 1, 9, 4],
       [2, 6, 7, 8, 8]])

In [49]:
a = np.arange(5)

In [41]:
a + 1

array([1, 2, 3, 4, 5])

In [43]:
b = (10 + (a * 2)) ** 2 / 100

In [44]:
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

In [45]:
a > 2

array([False, False, False,  True,  True])

In [46]:
a[ a > 2]

array([3, 4])

In [47]:
a.max()

np.int64(4)

In [48]:
a.sum()

np.int64(10)